# Generated by Django 6.0.2 on 2026-03-02 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('issuer', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('image', models.ImageField(blank=True, upload_to='certificates/')),
                ('file', models.FileField(blank=True, upload_to='certificates/pdf/')),
                ('url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Certificado',
                'ordering': ['order', '-date'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('authors', models.TextField()),
                ('journal', models.CharField(blank=True, max_length=200)),
                ('year', models.PositiveIntegerField()),
                ('url', models.URLField(blank=True)),
                ('abstract', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Publicação',
                'ordering': ['-year'],
            },
        ),
    ]
